### ISSUE TITLE
Past events shown on front page of site

### ISSUE THREAD

**Issue by rbowen** [OSAS/rh-events#141] opened 2015-11-23 21:13 UTC
Front page of community.redhat.com continues to show events after they are past.

![capture](https://cloud.githubusercontent.com/assets/255808/11349949/1a8ea658-91fd-11e5-97fc-1f8bfeaf793c.png)

**Comment by jasonbrooks** [comment] 2015-12-02 22:42
The events seem to be caught up again. It may be that there was a post on the 19th, and a post on the 24th, and no posts in between. You filed this bug on the 23rd, before that second post was pubbed, triggering a refresh of the events. If we've updated the events bit to update more frequently (not sure if that's happened yet), maybe that will address this issue.

**Comment by mscherer** [comment] 2015-12-03 09:06
yes, the core of the issue is that it classify series of events as if it was 1 single event starting at the first event, but still show all of them as 1 block, irrespective of the others events. 

I did dig in the code to understand, but I suspect what we are missing is what exactly we should be using series, and the semantic of the series, . The problematic code is around
https://github.com/OSAS/community-website/blob/master/lib/confcal.rb#L92

**Comment by rbowen** [comment] 2015-12-03 12:34
Jason, the site now shows events starting on the 30th of November, which was several days ago.

If you look at https://www.rdoproject.org/events/ it shows events starting today, and it does this regardless of when the last change to the site was pushed. That's what I expect to see on http://community.redhat.com/ - future events, not past ones.

If we are, in fact, rebuilding the site every 6 hours, then presumably that should have addressed the problem. It hasn't. So this is still a problem.

**Comment by garrett** [comment] 2015-12-11 14:45
Fixed in the community site:
* Public GitHub mirror: https://github.com/OSAS/community-website/commit/6a2132231c5cb17db19b7098c00db7025643dbe4 
* Internal behind-the-firewall GitLab repo: http://gitlab.osas.lab.eng.rdu2.redhat.com/garrett/community-middleman/commit/6a2132231c5cb17db19b7098c00db7025643dbe4

**Closed by garrett** 2015-12-11 14:45 UTC

**Comment by garrett** [comment] 2015-12-11 14:49
Also, quick bugfix @ https://github.com/OSAS/community-website/commit/455eb9c3b7ba3c349a0560741d71053e4a9a15ff — as the previous fix worked, but still counted the unseen, stale events against the future event counter limit.
